name: Day_24_Morning_Challenge
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: McLarenCollege <hello@mclarencollege.in>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0
dependencies:
  timezone: ^0.5.5
  time_machine: ^0.9.12
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

assets:
  - packages/timezone/data/latest.tzf